version: '3.7'

services:
  api:
    build:
      context: .
      args:
        - APP_ENV=dev # For local flow we will use test.txt as we will have to run test cases as well
      dockerfile: Dockerfile
    container_name: api
    env_file:
      - .env
    ports:
      - '8013:8000'
    tty: true
    links:
      - "db:database"
    depends_on:
      - db
    restart: always
    networks:
      - api-network
      
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - api-volume:/var/lib/postgresql/data
    ports:
      - "5413:5432"
    restart: always
    networks:
      - api-network


volumes:
  api-volume:

networks:
  api-network:
    driver: 'bridge'

